# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DHMVlaanderenDownloader
                                 A QGIS plugin
 Downloads and DHM Vlaanderen for specific area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-27
        copyright            : (C) 2020 by Rien Boydens
        email                : rien.boydens@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load DHMVlaanderenDownloader class from file DHMVlaanderenDownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .dhm_vlaanderen_downloader import DHMVlaanderenDownloader
    return DHMVlaanderenDownloader(iface)
