# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DHMVlaanderenDownloader
                                 A QGIS plugin
 Downloads and DHM Vlaanderen for specific area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Rien Boydens
        email                : rien.boydens@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Rien Boydens'
__date__ ='2020-12-01'
__copyright__ = '(C) 2020 by Rien Boydens'

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .dhm_vlaanderen_downloader_provider import DHMVlaanderenDownloaderProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class DHMVlaanderenDownloader:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        # Enable provider
        self.provider = None

    def initProcessing(self):
        self.provider = DHMVlaanderenDownloaderProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
       QgsApplication.processingRegistry().removeProvider(self.provider)
